name: Check and test the source code
on:
 pull_request:
  branches:
   - dev
jobs:
 test:
  name: Check the source code
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v3
   - uses: subosito/flutter-action@v2.10.0
     with:
      flutter-version: '3.13.0'
   - name: Install packages
     run: flutter pub get
   - name: Linter
     run: flutter analyze
   - name: Test
     run: flutter test
